### PR TITLE
More Spelling and Grammatical Corrections

### PR DESCRIPTION
**Pull request by ghost**
Continuation of minor spelling and grammatical corrections.

One code change to line 576 of
./NightgamesMod/nightgames/characters/Cassie.java. The sentence was:

```
"She leans in to lick and suck " + target.name()
+ " neck
```

I assume that it should read:

```
"She leans in to lick and suck " + target.name()
+ "'s neck
```

### CODE REVIEW

**Comment by nergantre** [comment]
Hey thanks for the corrections!

instead of using + "'s", try to prefer using target.possessive() or target.namePossessive() so it will rectify whether the target is a player or NPC (it'll use either "your", or "Angel's" or "her")

**Comment by ghost** [comment]
Ah, good to know, thanks. I'll correct that and keep it in mind for the future.

I'm going to be a bit slow until after the holidays this month, but I'll get that resolved and continue working as soon as possible.

**Comment by nergantre** [comment]
No problem, I'll actually be out on leave in a week or so until after the holidays as well, so it lines up nicely.

**Comment by ghost** [comment]
I'm going to close this pull request for now. I'm ~17 days behind on the commits, and need to get caught up. In its current state, this pull request should not be merged, so I'll resubmit it at the appropriate time.

**Pull request closed without merging**
